# -*- coding: utf-8 -*-
"""Integración OpenIA - Gradio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t_CSE_h19fIj-KzTak8jiI8ZJG7oQ6cu

# Tarea 3 Viculacion modelo con Gradio
"""

# Commented out IPython magic to ensure Python compatibility.
# # Instalación de librerías
# %%capture --no-stderr
# ##!pip install openai  al parecer la politicas cambiaron en la version 1 de openai hay que hacer un downgrade
# !pip install openai==0.28
# !pip install datasets evaluate transformers[sentencepiece]
# !pip install gradio

import openai
import getpass
import gradio as gr

# Configura tu clave de API de OpenAI
openai.api_key = getpass.getpass() #obtenemos la Api key no pude hacer funcionar

"""### Prueba de generacin de Imagen a partir de un texto"""

# Función para generar la imagen con OpenAI
def generar_imagen(prompt):
    response = openai.Image.create(
        prompt=prompt,
        n=1,
        size="512x512"

    )
    image_url = response['data'][0]['url']
    return image_url

# Crear la interfaz de Gradio
interface = gr.Interface(
    fn=generar_imagen,
    inputs=gr.Textbox(label="Descripción de la imagen"),
    outputs=gr.Image(label="Imagen generada"),
    title="Generador de Imágenes con OpenAI y radio de Julio Garcia",
    description="Introduce una descripción y generaré una imagen para ti:"
)

# Ejecutar la interfaz
interface.launch(debug=True) # deje el debg para que me muetre los errores en la ejecución

